Controllers/ClasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gimnasio_Brothers.Data;
using Gimnasio_Brothers.Models;

namespace Gimnasio_Brothers.Controllers
{
    public class ClasesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClasesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clases
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Clases.Include(c => c.IdactividadNavigation).Include(c => c.IdempleadoNavigation).Include(c => c.IdmatriculaNavigation).Include(c => c.IdsalaNavigation);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Clases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _context.Clases
                .Include(c => c.IdactividadNavigation)
                .Include(c => c.IdempleadoNavigation)
                .Include(c => c.IdmatriculaNavigation)
                .Include(c => c.IdsalaNavigation)
                .FirstOrDefaultAsync(m => m.Idclase == id);
            if (clase == null)
            {
                return NotFound();
            }

            return View(clase);
        }

        // GET: Clases/Create
        public IActionResult Create()
        {
            ViewData["Idactividad"] = new SelectList(_context.Actividades, "Idactividades", "Descripcion");
            ViewData["Idempleado"] = new SelectList(_context.Empleados, "Idempleado", "Apellidos");
            ViewData["Idmatricula"] = new SelectList(_context.Martriculas, "Idmatricula", "Idmatricula");
            ViewData["Idsala"] = new SelectList(_context.Salas, "Idsala", "Descripción");
            return View();
        }

        // POST: Clases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idclase,Idmatricula,Idactividad,Idempleado,Idsala,FechaClase,HoraInicio,HoraFin,Estado,Capacidad")] Clase clase)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idactividad"] = new SelectList(_context.Actividades, "Idactividades", "Descripcion", clase.Idactividad);
            ViewData["Idempleado"] = new SelectList(_context.Empleados, "Idempleado", "Apellidos", clase.Idempleado);
            ViewData["Idmatricula"] = new SelectList(_context.Martriculas, "Idmatricula", "Idmatricula", clase.Idmatricula);
            ViewData["Idsala"] = new SelectList(_context.Salas, "Idsala", "Descripción", clase.Idsala);
            return View(clase);
        }

        // GET: Clases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _context.Clases.FindAsync(id);
            if (clase == null)
            {
                return NotFound();
            }
            ViewData["Idactividad"] = new SelectList(_context.Actividades, "Idactividades", "Descripcion", clase.Idactividad);
            ViewData["Idempleado"] = new SelectList(_context.Empleados, "Idempleado", "Apellidos", clase.Idempleado);
            ViewData["Idmatricula"] = new SelectList(_context.Martriculas, "Idmatricula", "Idmatricula", clase.Idmatricula);
            ViewData["Idsala"] = new SelectList(_context.Salas, "Idsala", "Descripción", clase.Idsala);
            return View(clase);
        }

        // POST: Clases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idclase,Idmatricula,Idactividad,Idempleado,Idsala,FechaClase,HoraInicio,HoraFin,Estado,Capacidad")] Clase clase)
        {
            if (id != clase.Idclase)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClaseExists(clase.Idclase))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idactividad"] = new SelectList(_context.Actividades, "Idactividades", "Descripcion", clase.Idactividad);
            ViewData["Idempleado"] = new SelectList(_context.Empleados, "Idempleado", "Apellidos", clase.Idempleado);
            ViewData["Idmatricula"] = new SelectList(_context.Martriculas, "Idmatricula", "Idmatricula", clase.Idmatricula);
            ViewData["Idsala"] = new SelectList(_context.Salas, "Idsala", "Descripción", clase.Idsala);
            return View(clase);
        }

        // GET: Clases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _context.Clases
                .Include(c => c.IdactividadNavigation)
                .Include(c => c.IdempleadoNavigation)
                .Include(c => c.IdmatriculaNavigation)
                .Include(c => c.IdsalaNavigation)
                .FirstOrDefaultAsync(m => m.Idclase == id);
            if (clase == null)
            {
                return NotFound();
            }

            return View(clase);
        }

        // POST: Clases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clase = await _context.Clases.FindAsync(id);
            if (clase != null)
            {
                _context.Clases.Remove(clase);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClaseExists(int id)
        {
            return _context.Clases.Any(e => e.Idclase == id);
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConJs(Clase clase)
        {
            string mensaje = "Error al borrar registro";
            var encontrado = _context.Clases.Find(clase.Idclase);
            if (encontrado != null)
            {
                _context.Clases.Remove(encontrado);
                _context.SaveChanges();
                mensaje = "Registro borrado!";
            }

            return Json(new { result = true, mensaje = mensaje });
        }
    }
}

Views/Clases/Create.cshtml
@model Gimnasio_Brothers.Models.Clase

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear una Clase</h1>
<br>
<h4>Clases</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Idmatricula" class="control-label">Id Matricula</label>
                <select asp-for="Idmatricula" class="form-control" asp-items="ViewBag.Idmatricula"></select>
            </div>
            <div class="form-group">
                <label asp-for="Idactividad" class="control-label">Nombre de la Actividad</label>
                <select asp-for="Idactividad" class="form-control" asp-items="ViewBag.Idactividad"></select>
            </div>
            <div class="form-group">
                <label asp-for="Idempleado" class="control-label">Id Empleado</label>
                <select asp-for="Idempleado" class="form-control" asp-items="ViewBag.Idempleado"></select>
            </div>
            <div class="form-group">
                <label asp-for="Idsala" class="control-label">Id Sala</label>
                <select asp-for="Idsala" class="form-control" asp-items="ViewBag.Idsala"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaClase" class="control-label">Fecha de la Clase</label>
                <input type="date" asp-for="FechaClase" class="form-control" />
                <span asp-validation-for="FechaClase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraInicio" class="control-label">Hora de Inicio</label>
                <input type="time" asp-for="HoraInicio" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraFin" class="control-label">Hora de Salida</label>
                <input type="time" asp-for="HoraFin" class="form-control" />
                <span asp-validation-for="HoraFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label">Estado de la Clase</label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacidad" class="control-label">Capacidad de la Clase</label>
                <input type="number" asp-for="Capacidad" class="form-control" />
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success  bi bi-plus-circle"> Agregar Clases</button>
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a asp-action="Index" class="btn btn-warning"> <i class="bi bi-arrow-return-left"></i> Regresar a Clases</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Clases/Delete.cshtml
@model Gimnasio_Brothers.Models.Clase

@{
    ViewData["Title"] = "Eliminar Clase";
}

<h1>Elimniar Clase</h1>
<br>
<h3>¿Esta seguro de eliminar esta actividad?</h3>
<div>
    <h4>Clase</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Fecha clase
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaClase)
        </dd>
        <dt class="col-sm-2">
            Inicio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>
        <dt class="col-sm-2">
            Fin
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoraFin)
        </dd>
        <dt class="col-sm-2">
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            Capacidad
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidad)
        </dd>
        <dt class="col-sm-2">
            Actividad
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdactividadNavigation.Descripcion)
        </dd>
        <dt class="col-sm-2">
            Empleado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdempleadoNavigation.Apellidos)
        </dd>
        <dt class="col-sm-2">
            Matricula
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdmatriculaNavigation.Idmatricula)
        </dd>
        <dt class="col-sm-2">
            Sala
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdsalaNavigation.Descripción)
        </dd>
    </dl>

    <form asp-action="Delete" id="AlertaEmergente">
        <input type="hidden" asp-for="Idclase" />
        <input type="button" id="btnDeleteJs" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning  bi bi-arrow-return-left "> Regresar a  Empleados  </a>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        async function fetchData() {

            const dataform = new FormData(document.querySelector('#AlertaEmergente'));
            const response = await fetch('/Clases/DeleteConJs',
                {
                    method: 'Delete',
                    body: dataform
                });
            const result = await response.json();
            return result;
        }

        async function deleteClases() {
            try {
                var response = await fetchData();
                if (response.result) {
                    console.log(response.result);
                    Swal.fire({
                        title: "El registro fue borrado exitosamente!",
                        icon: "info",
                        timer: 1500,
                        timerProgressBar: false,
                        didOpen: () => {
                            Swal.showLoading();
                            timerInterval = setInterval(() => {
                            }, 100);
                        },
                        willClose: () => {
                            clearInterval(timerInterval);
                        }
                    }).then((result) => {
                        window.location.href = '@Url.Action("Index", "Clases")'
                    });

                } else {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: response.mensaje,
                        showConfirmButton: false,
                        timer: 1500
                    });
                }
            } catch (error) {
                console.log(error);
            }
        }

        document.addEventListener("DOMContentLoaded", () => {
            document.querySelector("#btnDeleteJs").addEventListener('click', () => {
                Swal.fire({
                    title: "Está seguro de eliminar el registro?",
                    text: "Tome en cuenta que es un proceso irreversible",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, borrar!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteClases();
                    }
                });
            })
        });
    </script>

}

Views/Clases/Details.cshtml
@model Gimnasio_Brothers.Models.Clase
@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>
<br>
<div>
    <h4>Clase</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaClase)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaClase)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HoraInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HoraFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoraFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdactividadNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdactividadNavigation.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdempleadoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdempleadoNavigation.Apellidos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdmatriculaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdmatriculaNavigation.Idmatricula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdsalaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdsalaNavigation.Descripción)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Idclase" class="btn btn-danger"> <i class="bi bi-pencil-fill"> Editar</i> </a> |
    <a asp-action="Index" class="btn btn-warning"> <i class="bi bi-arrow-return-left"></i> Volver a Clases</a>
</div>

Views/Clases/Edit.cshtml
@model Gimnasio_Brothers.Models.Clase

@{
    ViewData["Title"] = "Editar Clase";
}

<h1>Editar</h1>
<br>
<h4>Editar Clase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idclase" />
            <div class="form-group">
                <label asp-for="Idmatricula" class="control-label">Id de Matricula</label>
                <select asp-for="Idmatricula" class="form-control" asp-items="ViewBag.Idmatricula"></select>
                <span asp-validation-for="Idmatricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idactividad" class="control-label">Id de Actividad</label>
                <select asp-for="Idactividad" class="form-control" asp-items="ViewBag.Idactividad"></select>
                <span asp-validation-for="Idactividad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idempleado" class="control-label">Id De Empleado</label>
                <select asp-for="Idempleado" class="form-control" asp-items="ViewBag.Idempleado"></select>
                <span asp-validation-for="Idempleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idsala" class="control-label">Id de Sala</label>
                <select asp-for="Idsala" class="form-control" asp-items="ViewBag.Idsala"></select>
                <span asp-validation-for="Idsala" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaClase" class="control-label">Fecha de la Clase</label>
                <input type="date" asp-for="FechaClase" class="form-control" />
                <span asp-validation-for="FechaClase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraInicio" class="control-label">Hora de Inicio</label>
                <input type="time" asp-for="HoraInicio" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraFin" class="control-label">Hora de salida</label>
                <input type="time" asp-for="HoraFin" class="form-control" />
                <span asp-validation-for="HoraFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacidad" class="control-label"></label>
                <input asp-for="Capacidad" class="form-control" />
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="bi bi-plus-circle"> Guardar</i></button>
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"> Regresar a Clases</i></a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Clases/Index.cshtml
@model IEnumerable<Gimnasio_Brothers.Models.Clase>

@{
    ViewData["Title"] = "Clase";
}

<h1>Clases</h1>
<br>
<p>
    <a asp-action="Create" class="btn btn-success"> <i class="bi bi-plus-lg"></i>Agregar Nueva Clase</a>
</p>
<table class="table" id="tblClases">
    <thead>
        <tr>
            <th>
                Fecha
            </th>
            <th>
                Inicio
            </th>
            <th>
                Fin
            </th>
            <th>
                Estado
            </th>
            <th>
                Capacidad
            </th>
            <th>
                Actividad
            </th>
        
            <th>
                Sala
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaClase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraInicio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraFin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Capacidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdactividadNavigation.Descripcion)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.IdsalaNavigation.Descripción)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Idclase" class="btn btn-warning"> <i class="bi bi-pencil-fill"> Editar</i> </a> |
                    <a asp-action="Details" asp-route-id="@item.Idclase" class="btn btn-secondary"> <i class="bi bi-info-circle-fill"> Ver</i> </a> |
                    <a asp-action="Delete" asp-route-id="@item.Idclase" class="btn btn-danger"> <i class="bi bi-x-circle-fill"> Borrar</i> </a>
                </td>
            </tr>
        }
    </tbody>
</table>


@section scripts {
    <script>
        let table = new DataTable('#tblClases', {
            "language": {
                "decimal": "",
                "emptyTable": "No hay registros",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            "width": "100%"
        });
    </script>
}