Models/Proveedore.cs
using System;
using System.Collections.Generic;

namespace Gimnasio_Brothers.Models;

public partial class Proveedore
{
    public int Idprovedores { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string CorreoElectronico { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();

    public virtual ICollection<ProductosVentum> ProductosVenta { get; set; } = new List<ProductosVentum>();
}

Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gimnasio_Brothers.Data;
using Gimnasio_Brothers.Models;

namespace Gimnasio_Brothers.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProveedoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Proveedores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proveedores.ToListAsync());
        }

        // GET: Proveedores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.Idprovedores == id);
            if (proveedore == null)
            {
                return NotFound();
            }

            return View(proveedore);
        }

        // GET: Proveedores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idprovedores,Nombre,Telefono,CorreoElectronico,Estado")] Proveedore proveedore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proveedore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proveedore);
        }

        // GET: Proveedores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores.FindAsync(id);
            if (proveedore == null)
            {
                return NotFound();
            }
            return View(proveedore);
        }

        // POST: Proveedores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idprovedores,Nombre,Telefono,CorreoElectronico,Estado")] Proveedore proveedore)
        {
            if (id != proveedore.Idprovedores)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proveedore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProveedoreExists(proveedore.Idprovedores))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proveedore);
        }

        // GET: Proveedores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.Idprovedores == id);
            if (proveedore == null)
            {
                return NotFound();
            }

            return View(proveedore);
        }

        // POST: Proveedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proveedore = await _context.Proveedores.FindAsync(id);
            if (proveedore != null)
            {
                _context.Proveedores.Remove(proveedore);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProveedoreExists(int id)
        {
            return _context.Proveedores.Any(e => e.Idprovedores == id);
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConJs(Proveedore preovedor)
        {
            string mensaje = "Error al borrar registro";
            var encontrado = _context.Clases.Find(preovedor.Idprovedores);
            if (encontrado != null)
            {
                _context.Clases.Remove(encontrado);
                _context.SaveChanges();
                mensaje = "Registro borrado!";
            }

            return Json(new { result = true, mensaje = mensaje });
        }
    }
}

Views/Proveedores/Create.cshtml
@model Gimnasio_Brothers.Models.Proveedore

@{
    ViewData["Title"] = "Agregar";
}

<h1>Agregar Provedor</h1>
<br>
<h4>Provedor</h4>
<hr />
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label">Correo</label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success  bi bi-plus-circle"> Agregar Pedido</button>
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"></i> Regresar a Provedores</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proveedores/Delete.cshtml
@model Gimnasio_Brothers.Models.Proveedore

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar Provedor</h1>
<br>
<h3>¿Esta Seguro de Eliminar?</h3>
<br>
<div>
    <h4>Proveedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            Correo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete" id="AlertaEmergente">
        <input type="hidden" asp-for="Idprovedores" />
        <input type="button" id="btnDeleteJs" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning  bi bi-arrow-return-left "> Regresar a la lista</a>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        async function fetchData() {

            const dataform = new FormData(document.querySelector('#AlertaEmergente'));
            const response = await fetch('/Proveedores/DeleteConJs',
                {
                    method: 'Delete',
                    body: dataform
                });
            const result = await response.json();
            return result;
        }

        async function deleteClases() {
            try {
                var response = await fetchData();
                if (response.result) {
                    console.log(response.result);
                    Swal.fire({
                        title: "El registro fue borrado exitosamente!",
                        icon: "info",
                        timer: 1500,
                        timerProgressBar: false,
                        didOpen: () => {
                            Swal.showLoading();
                            timerInterval = setInterval(() => {
                            }, 100);
                        },
                        willClose: () => {
                            clearInterval(timerInterval);
                        }
                    }).then((result) => {
                        window.location.href = '@Url.Action("Index", "Proveedores")'
                    });

                } else {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: response.mensaje,
                        showConfirmButton: false,
                        timer: 1500
                    });
                }
            } catch (error) {
                console.log(error);
            }
        }

        document.addEventListener("DOMContentLoaded", () => {
            document.querySelector("#btnDeleteJs").addEventListener('click', () => {
                Swal.fire({
                    title: "Está seguro de eliminar el registro?",
                    text: "Tome en cuenta que es un proceso irreversible",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, borrar!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteClases();
                    }
                });
            })
        });
    </script>

}

Views/Proveedores/Details.cshtml
@model Gimnasio_Brothers.Models.Proveedore

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles del Provedor</h1>
<br>
<div>
    <h4>Proveedor</h4>
    <hr />
    <br>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            Correo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<br>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Idprovedores" class="btn btn-danger"> <i class="bi bi-pencil-fill"> Editar</i> </a> |
    <a asp-action="Index" class="btn btn-warning" class="bi bi-arrow-return-left"> Regresar a Provedor</a>
</div>

Views/Proveedores/Edit.cshtml
@model Gimnasio_Brothers.Models.Proveedore

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar Provedor</h1>
<br>
<h4>Proveedor</h4>
<hr />
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idprovedores" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label">Correo</label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="bi bi-plus-circle"> Guardar</i></button>
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a asp-action="Index" class="btn btn-warning" class="bi bi-arrow-return-left"> Regresar a Provedor</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proveedores/Index.cshtml
@model IEnumerable<Gimnasio_Brothers.Models.Proveedore>

@{
    ViewData["Title"] = "Provedor";
}

<h1>Provedores</h1>
<br>
<p>
    <a asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"> Agregar nuevo preoveedor</i></a>
</p>
<br>
<table class="table" id="tblProveedore">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                Correo
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Idprovedores" class="btn btn-warning"><i class="bi bi-pencil"> Editar</i></a> |
                    <a asp-action="Details" asp-route-id="@item.Idprovedores" class="btn btn-secondary"><i class="bi bi-info-circle"> Ver</i></a> |
                    <a asp-action="Delete" asp-route-id="@item.Idprovedores" class="btn btn-danger"><i class="bi bi-x-circle"> Eliminar</i></a>
            </td>
        </tr>
}
    </tbody>
</table>

@section scripts {
    <script>
        let table = new DataTable('#tblProveedore', {
        "language": {
        "decimal": "",
        "emptyTable": "No hay registros",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
        "first": "Primero",
        "last": "Ultimo",
        "next": "Siguiente",
        "previous": "Anterior"
        }
        },
        "width": "100%"
        });
    </script>
}