Controllers/CategoriaMembresiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gimnasio_Brothers.Data;
using Gimnasio_Brothers.Models;

namespace Gimnasio_Brothers.Controllers
{
    public class CategoriaMembresiasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriaMembresiasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CategoriaMembresias
        public async Task<IActionResult> Index()
        {
            return View(await _context.CategoriaMembresia.ToListAsync());
        }

        // GET: CategoriaMembresias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaMembresium = await _context.CategoriaMembresia
                .FirstOrDefaultAsync(m => m.IdcategoriaMembresia == id);
            if (categoriaMembresium == null)
            {
                return NotFound();
            }

            return View(categoriaMembresium);
        }

        // GET: CategoriaMembresias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriaMembresias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdcategoriaMembresia,Descripcion,Precio,Nombre")] CategoriaMembresium categoriaMembresium)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoriaMembresium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaMembresium);
        }

        // GET: CategoriaMembresias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaMembresium = await _context.CategoriaMembresia.FindAsync(id);
            if (categoriaMembresium == null)
            {
                return NotFound();
            }
            return View(categoriaMembresium);
        }

        // POST: CategoriaMembresias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdcategoriaMembresia,Descripcion,Precio,Nombre")] CategoriaMembresium categoriaMembresium)
        {
            if (id != categoriaMembresium.IdcategoriaMembresia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoriaMembresium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaMembresiumExists(categoriaMembresium.IdcategoriaMembresia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaMembresium);
        }

        // GET: CategoriaMembresias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaMembresium = await _context.CategoriaMembresia
                .FirstOrDefaultAsync(m => m.IdcategoriaMembresia == id);
            if (categoriaMembresium == null)
            {
                return NotFound();
            }

            return View(categoriaMembresium);
        }

        // POST: CategoriaMembresias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoriaMembresium = await _context.CategoriaMembresia.FindAsync(id);
            if (categoriaMembresium != null)
            {
                _context.CategoriaMembresia.Remove(categoriaMembresium);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaMembresiumExists(int id)
        {
            return _context.CategoriaMembresia.Any(e => e.IdcategoriaMembresia == id);
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConJs(CategoriaMembresium categoria)
        {
            string mensaje = "Error al borrar registro";
            var encontrado = _context.CategoriaMembresia.Find(categoria.IdcategoriaMembresia);
            if (encontrado != null)
            {
                _context.CategoriaMembresia.Remove(encontrado);
                _context.SaveChanges();
                mensaje = "Registro borrado!";
            }

            return Json(new { result = true, mensaje = mensaje });
        }
    }
}

Views/CategoriaMembresias/Create.cshtml
@model Gimnasio_Brothers.Models.CategoriaMembresium

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Membresia</h1>
<br>
<h4>Categoria de membresía</h4>
<hr />
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success  bi bi-plus-circle"> Agregar Membresia</button>
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"> Regresar a Categoria Membresia</i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CategoriaMembresias/Delete.cshtml
@model Gimnasio_Brothers.Models.CategoriaMembresium

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Está seguro que desea eliminar la categoría?</h3>
<div>
    <h4>CategoriaMembresium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete" id="formulario">
        <input type="hidden" asp-for="IdcategoriaMembresia" />
        <input type="button" id="btnDeleteJs" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"> Regresar a Membresia</i></a>
    </form>
</div>

@section Scripts {
@{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        async function fetchData() {
            
            const dataform = new FormData(document.querySelector('#formulario'));
            const response = await fetch('/CategoriaMembresias/DeleteConJs',
                {
                    method: 'Delete',
                    body: dataform
                });
            const result = await response.json();
            return result;
        }

        async function deleteCategoria() {

            try {
                var response = await fetchData();
                if (response.result) {
                    console.log(response.result);
                    Swal.fire({
                        title: "El registro fue borrado exitosamente!",
                        icon: "info",
                        timer: 2000,
                        timerProgressBar: false,
                        didOpen: () => {
                            Swal.showLoading();
                            timerInterval = setInterval(() => {
                            }, 100);
                        },
                        willClose: () => {
                            clearInterval(timerInterval);
                        }
                    }).then((result) => {
                         window.location.href = '@Url.Action("Index", "CategoriaMembresias")'
                    });
                  
                } else {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: response.mensaje,
                        showConfirmButton: false,
                        timer: 1500
                    });
                }
            } catch (error) {
                console.log(error);
            }

        }
        document.addEventListener("DOMContentLoaded", () => {
            document.querySelector("#btnDeleteJs").addEventListener('click', () => {
                Swal.fire({
                    title: "Está seguro de eliminar el registor?",
                    text: "Tome en cuenta que es un proceso irreversible",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, borrar!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteCategoria();
                    }
                });
            })
        });
    </script>
}

Views/CategoriaMembresias/Details.cshtml
@model Gimnasio_Brothers.Models.CategoriaMembresium

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>CategoriaMembresium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdcategoriaMembresia" class="btn btn-danger"><i class="bi bi-pencil"> Editar</i></a> |
    <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"> Regresar a Membresia</i></a>
</div>

Views/CategoriaMembresias/Edit.cshtml
@model Gimnasio_Brothers.Models.CategoriaMembresium

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar categoría</h1>
<br>
<h4>Categoria Membresia</h4>
<hr />
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdcategoriaMembresia" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success  bi bi-plus-circle"> Agregar Membresia</button>
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a asp-action="Index" class="btn btn-warning"><i class="bi bi-arrow-return-left"> Regresar a Membresia</i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CategoriaMembresias/Index.cshtml
@model IEnumerable<Gimnasio_Brothers.Models.CategoriaMembresium>

@{
    ViewData["Title"] = "Membresías";
}

<h1>Lista de tipos de Membresía</h1>
<br>
<p>
    <a asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"> Crear nueva categoría</i></a>
</p>
<br>
<table class="table" id="tblCategoriaMemb">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <br>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.IdcategoriaMembresia" class="btn btn-warning"><i class="bi bi-pencil"> Editar</i></a> |
                    <a asp-action="Details" asp-route-id="@item.IdcategoriaMembresia" class="btn btn-secondary"><i class="bi bi-info-circle"> Ver</i></a> |
                <a asp-action="Delete" asp-route-id="@item.IdcategoriaMembresia" class="btn btn-danger"><i class="bi bi-trash"> Borrar</i></a>
            </td>
        </tr>
}
    </tbody>
</table>

@section scripts {
    <script>
        let table = new DataTable('#tblCategoriaMemb', {
        "language": {
            "decimal": "",
            "emptyTable": "No hay registros",
            "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
            "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
            "infoFiltered": "(Filtrado de _MAX_ total entradas)",
            "infoPostFix": "",
            "thousands": ",",
            "lengthMenu": "Mostrar _MENU_ Entradas",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",
            "search": "Buscar:",
            "zeroRecords": "Sin resultados encontrados",
            "paginate": {
                "first": "Primero",
                "last": "Ultimo",
                "next": "Siguiente",
                "previous": "Anterior"
            }
        },
        "width": "100%"
        });
    </script>
}